from app.models.highlight import HighlightType
from app.models.short import ExportPlatform
from app.services.pipeline.types import DetectedMoment

HASHTAG_MAP: dict[HighlightType, list[str]] = {
    HighlightType.SIX: ["#Cricket", "#Six", "#CricketShorts", "#IPL"],
    HighlightType.WICKET: ["#Wicket", "#Cricket", "#CricketReels"],
    HighlightType.CATCH: ["#Catch", "#Cricket", "#AmazingCatch"],
    HighlightType.HAT_TRICK: ["#HatTrick", "#Cricket", "#Bowling"],
}


def build_hashtags(moment: DetectedMoment, league: str | None) -> str:
    tags = list(HASHTAG_MAP.get(moment.highlight_type, ["#Cricket", "#CricketShorts"]))
    if league == "ipl":
        tags.extend(["#IPL", "#IPL2025"])
    elif league == "icc":
        tags.extend(["#ICC", "#WorldCup"])
    tags.append("#CricketShortsAI")
    return " ".join(dict.fromkeys(tags))


def build_description(moment: DetectedMoment, league: str | None) -> str:
    parts = [moment.caption, moment.title]
    if moment.player_name:
        parts.append(f"⭐ {moment.player_name}")
    if moment.team_name:
        parts.append(f"🏏 {moment.team_name}")
    if moment.commentary_snippet:
        parts.append(f'"{moment.commentary_snippet}"')
    parts.append("Auto-generated by Cricket Shorts AI")
    return "\n".join(parts)


def platform_label(platform: ExportPlatform) -> str:
    return {
        ExportPlatform.YOUTUBE_SHORTS: "YouTube Shorts",
        ExportPlatform.TIKTOK: "TikTok",
        ExportPlatform.INSTAGRAM_REELS: "Instagram Reels",
        ExportPlatform.FACEBOOK_REELS: "Facebook Reels",
    }[platform]
